plugin:
  lang: en_US
  tag: '&fCreativeManager &7>>'
  debug-mode: false
  check-update: true
  antispam-tick: 5
  save-interval: 300
  stop-inventory-save: false

multi-inventories:
  _GLOBAL:
    survival: survival
    adventure: survival
    creative: creative
  world_nether:
    survival: survival_nether
    adventure: survival_nether
    creative: creative_nether

protections:
  logblock:
    enabled: true
  build:
    enabled: false
  container:
    enabled: true
  spawn:
    enabled: true
    multi-block:
      wither: true
      snowman: true
  drop:
    enabled: true
  pickup:
    enabled: true
  entity:
    enabled: true
  combat:
    pvp:
      enabled: true
    pve:
      enabled: true
  throw:
    enabled: true
  player-claim:
    enabled: true
    plugins:
      - WorldGuard
      - GriefPrevention
      - Lands
  itemtrack:
    enabled: true
    displayname: '&#73e1ff{ITEM}'
    lore:
      - '&6&l💎 Items informations'
      - ''
      - ' &7> &f&lItem : &r&7{ITEM}'
      - ' &7> &f&lCreator &7: &r&7{PLAYER}'
      - ' &7> &f&lCreator UUID &7: &r&7{UUID}'
  data-remover:
    enabled: false
    type:
      ENCHANT:
        enabled: true
        allow-unsafe: false
        custom-max:
          MENDING: 10
        remover:
          list-type: WHITELIST
          list: []
      NBT:
        enabled: true
        remover:
          list-type: WHITELIST
          list: []
      POTION_EFFECT:
        enabled: true
        remover:
          list-type: WHITELIST
          list: [ ]
      NAME_SPACED_KEY:
        enabled: true
        remover:
          list-type: WHITELIST
          list: [ ]
      ITEM_FLAG:
        enabled: true
        remover:
          list-type: WHITELIST
          list: [ ]
  creative_armor:
    enabled: false
    armors:
      helmet:
        name: '&6Creative Helmet'
        lore:
          - '&7This creative Helmet is bind to your Game mode !'
        material: BEDROCK
        model-data: 0
        items-adder: ''
      chest-plate:
        name: '&6Creative Chestplate'
        lore:
          - '&7This &6Creative Chestplate&7 is bind to your Game mode !'
        material: LEATHER_CHESTPLATE
        leather-color:
          red: 255
          green: 255
          blue: 255
        model-data: 0
        items-adder: ''
      leggings:
        name: '&6Creative Leggings'
        lore:
          - '&7This &6Creative Leggings&7 is bind to your Game mode !'
        material: CHAINMAIL_LEGGINGS
        model-data: 0
        items-adder: ''
      boots:
        name: '&6Creative Boots'
        lore:
          - '&7This &6Creative Boots&7 is bind to your Game mode !'
        material: CHAINMAIL_BOOTS
        model-data: 0
        items-adder: ''
  custom:
    enabled: false
    commands:
      type: BLACKLIST
      list: []
    place:
      type: BLACKLIST
      list: []
    break:
      type: BLACKLIST
      list: []
    item-use:
      type: BLACKLIST
      list: []
    block-use:
      type: BLACKLIST
      list: []
    store-item:
      type: BLACKLIST
      list: []
    nbt:
      type: WHITELIST
      list:
        - 'down'
        - 'east'
        - 'north'
        - 'south'
        - 'up'
        - 'west'
