name: CreativeManager2
version: '${project.version}'
authors:
  - K0bus
website: https://github.com/K0bus/CreativeManager2/
main: fr.k0bus.creativemanager2.CreativeManager2
api-version: '1.19'
dependencies:
  - name: WorldGuard
    required: false
  - name: Lands
    required: false
  - name: GriefPrevention
    required: false
  - name: PlaceholderAPI
    required: false
  - name: NBTAPI
    required: true
  - name: ItemsAdder
    required: false
  - name: Oraxen
    required: false
  - name: ItemJoin
    required: false