name: CreativeManager2
version: '${project.version}'
main: fr.k0bus.creativemanager2.CreativeManager2
api-version: '1.20'
dependencies:
  server:
    WorldGuard:
      load: BEFORE
      required: false
      join-classpath: true
    Lands:
      load: BEFORE
      required: false
      join-classpath: true
    GriefPrevention:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true