name: CreativeManager2
version: '${project.version}'
main: fr.k0bus.creativemanager2.CreativeManager2
api-version: '1.20'
libraries:
  - net.kyori:adventure-api:4.19.0
  - net.kyori:adventure-platform-bukkit:4.3.4
depend:
  - NBTAPI
softdepend:
  - WorldGuard
  - Lands
  - GriefPrevention
  - PlaceholderAPI
commands:
  cm2:
    usage: "/cm2"
    permission: "cm2.admin"
    description: "CreativeManager2 commands"